# Generated by Django 5.2.17 on 2026-09-29 17:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0003_relaystate_grid_import_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnergyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "solar_power",
                    models.FloatField(
                        default=0.0, help_text="Solar power generation in Watts"
                    ),
                ),
                (
                    "load_power",
                    models.FloatField(
                        default=0.0, help_text="Power consumption of the load in Watts"
                    ),
                ),
                (
                    "battery_voltage",
                    models.FloatField(
                        default=0.0, help_text="Battery voltage in Volts"
                    ),
                ),
                (
                    "battery_current",
                    models.FloatField(
                        default=0.0, help_text="Battery current in Amperes"
                    ),
                ),
                (
                    "battery_soc",
                    models.FloatField(
                        default=0.0, help_text="Battery State of Charge (%)"
                    ),
                ),
                (
                    "battery_temperature",
                    models.FloatField(
                        default=0.0, help_text="Battery temperature in Celsius"
                    ),
                ),
                (
                    "grid_power",
                    models.FloatField(default=0.0, help_text="Grid power in Watts"),
                ),
                (
                    "generator_power",
                    models.FloatField(
                        default=0.0, help_text="Generator power in Watts"
                    ),
                ),
                (
                    "fuel_level",
                    models.FloatField(default=0.0, help_text="Fuel level (%)"),
                ),
                (
                    "outside_temperature",
                    models.FloatField(
                        default=0.0, help_text="Outside temperature in Celsius"
                    ),
                ),
                (
                    "weather_condition",
                    models.CharField(
                        default="Unknown",
                        help_text="Weather condition (e.g. Sunny, Cloudy)",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Energy Data",
                "ordering": ["-timestamp"],
            },
        ),
    ]
